trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
-stage: Build
  jobs:
  -jobs: FirstJob
   steps:
   - bash: echo Build FirstJob
  -jobs: SecondJob
   steps:
   - bash: echo Build SecondJob
-stage: DevDeploy
  jobs:
  -jobs: DevDeployJob
   steps:
   - bash: echo Build DevDeployJob
-stage: QaDeploy
  jobs:
  -jobs: QaDeployJob
   steps:
   - bash: echo Build QaDeployJob
-stage: ProdDeploy
  jobs:
  -jobs: ProdDeployJob
   steps:
   - bash: echo Build ProdDeployJob

steps:
- script: echo Job1 Step1!
  displayName: 'Run a one-line script'
